management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: voting_app
    description: Voting app.
    author: For interview
    version: '@project.version@'
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev