management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: forecast_app
    description: Forecast app.
    author: For interview
    version: '@project.version@'
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev

forecast:
  api:
    url: "https://archive-api.open-meteo.com/v1/archive?hourly=precipitation&daily=sunrise&timezone=auto"